name: Destroy infrastructure
on: [workflow_dispatch]
jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
      - name: Destroy terraform infrastructure
        run: |
          cd terraform
          terraform init
          terraform destroy -auto-approve
